import type { Metadata, Viewport } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { SITE } from "@/lib/site";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { FloatingActions } from "@/components/layout/FloatingActions";
import { ExitIntentPopup } from "@/components/layout/ExitIntentPopup";
import { Analytics } from "@/components/analytics/Analytics";
import { Schema } from "@/components/seo/Schema";
import { organizationSchema, websiteSchema } from "@/lib/schema";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} | ${SITE.tagline}`,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  keywords: [
    "Property Dealer Gurgaon",
    "Property Dealer Palam Vihar",
    "Builder Floors Palam Vihar",
    "Real Estate Consultant Gurgaon",
    "Flats in Sector 23 Gurgaon",
    "Plots in Palam Vihar",
    "Property in Sector 21 Gurgaon",
    "Property in Sector 22 Gurgaon",
    "Builder Floors Gurgaon",
    "Real Estate Agent Palam Vihar",
  ],
  authors: [{ name: SITE.name }],
  creator: SITE.name,
  publisher: SITE.name,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE.url,
    siteName: SITE.name,
    title: `${SITE.name} | ${SITE.tagline}`,
    description: SITE.description,
    // og:image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE.name} | ${SITE.tagline}`,
    description: SITE.description,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  // favicon + apple-icon auto-generated by app/icon.tsx & app/apple-icon.tsx
  verification: { google: "" },
};

export const viewport: Viewport = {
  themeColor: "#0B1F3A",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-IN" className={`${inter.variable} ${playfair.variable}`}>
      <body>
        <Schema json={organizationSchema()} />
        <Schema json={websiteSchema()} />
        <Header />
        <main className="min-h-screen pb-16 md:pb-0">{children}</main>
        <Footer />
        <FloatingActions />
        <ExitIntentPopup />
        <Analytics />
      </body>
    </html>
  );
}
